### ISSUE TITLE
Arch Linux installation failure

### ISSUE THREAD

**Issue by vmatyushin** [SkidanovAlex/CtrlK#34]
Python version:

```
 ~ % python
Python 3.4.3 (default, Mar 25 2015, 17:13:50) 
[GCC 4.9.2 20150304 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

```
# pip install ctrlk
Collecting ctrlk
  Using cached ctrlk-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b1q9568b/ctrlk
```

Manual installation attempt:

```
 ~ % cd py-ctrlk/
 ~/py-ctrlk % python setup.py build
  File "setup.py", line 21
    print os.getenv("LD_LIBRARY_PATH")
           ^
SyntaxError: invalid syntax
```

**Comment by Stuv7CB** [comment]
Try to use
`sudo pip2 install ctrlk`
Arch Linux uses python 3.5 but crtlk uses syntax of python 2
